### ISSUE TITLE
Aggregate limit greater than 10000 in nredisearch

### ISSUE THREAD

**Issue by Ekotenggara** [StackExchange/NRediSearch#27]
Hi everyone,

Is it possible to set limi greater than 10000 in nredisearch aggregate?
My aggregate can grow to be more than 1 million, can nredisearch to this? Can I remove the limit forever?
I have redis installed in local docker in windows. 

![image](https://user-images.githubusercontent.com/29136781/164959828-2d35ebbe-d56b-4528-97b6-368239d20a1a.png)

Thank you

**Comment by Ekotenggara** [comment]
I have figured out by using 
FT.CONFIG SET MAXSEARCHRESULTS -1 
FT.CONFIG SET MAXAGGREGATERESULTS -1 
in the cli will enable me to get higher limit.
However, is there any way to not specify the limit at all (since I am not sure how many the results are)? At the moment, I will still only get10 results if I don't specify the limit.
Thank you.

**Comment by slorello89** [comment]
Hi @Ekotenggara - This limit is something that exists in the configuration so you're right, you can either use an `FT.CONFIG` - or add a configuration flag when you are loading RediSearch to remove those configuration settings.

The accurate, but somewhat disappointing, answer to your second question is that no, you cannot specify no-limit. There are reasons behind this as searches and aggregations can become a pretty accurate foot-gun when you start enumerating massive data sets given that Redis is single-threaded and needs to service those commands one at a time. Your best bet is to use the [cursor-API](https://redis.io/docs/stack/search/reference/aggregations/#cursor-api) with very large page sizes to paginate massive aggregations.

**Comment by Ekotenggara** [comment]
Thank you so much for your help :)

**Comment by ivan-kleshnin** [comment]
> Your best bet is to use the [cursor-API](https://redis.io/docs/stack/search/reference/aggregations/#cursor-api) with very large page sizes to paginate massive aggregations.

The cursor API defaults to returning 10 documents: https://github.com/RediSearch/RediSearch/issues/1709 when `SORTBY` is present in the query. We have to pass `LIMIT offset limit`. So 10K hard cap affects cursor based API! Any suggestion on how to workaround that?
